### ISSUE TITLE
Images in www/ folder not accessible from `secure_rmd()`

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished#193]
e.g. the following does not work if the below image is in the www folder.  We may need to manually `addResourcePath()` the www/ folder in `secure_rmd()`

```yaml
title: "Biodiversity Monitoring"
subtitle: "Purchaser Summary"
date: "`r Sys.Date()`"
polished:
  sign_in_page:
    logo: "img/my_image.png"
```
